before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-setuptools python3-dev python-virtualenv python-pip firefox node-less automake libtool libreadline6 libreadline6-dev zlib1g-dev libxml2 libxml2-dev make build-essential libssl-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libpq-dev
language: python
python:
  - "3.4"
install:
  - "pip install hitch"
  - "cd tests"
  - "hitch init"
script:
  - "hitch test . --settings ci.settings"
